<?php
/**
 * Blocks
 *
 * @package      WP040 Demo
 * @author       Rob Migchels <rob@migchels.me>
 * @license      GPL-2.0+
 **/

namespace wp040\Blocks;

/**
 * Add new block categories and move them to the top of the categories.
 *
 * @param array $categories all block categories.
 * @param array $post current post.
 * @return array array of all categories.
 * @author Rob Migchels <rob@migchels.me>
 */
function block_category( $categories, $post ) {

	array_unshift(
		$categories,
		array(
			'slug'  => 'wp040',
			'title' => __( 'WP040 Demo', 'wp040' ),
		)
	);

	return $categories;
}
add_filter( 'block_categories_all', __NAMESPACE__ . '\\block_category', 10, 2 );

/**
 * Load Blocks.
 *
 * @return void
 * @author Rob Migchels <rob@migchels.me>
 */
function load_blocks() {
	$blocks = get_blocks();
	foreach ( $blocks as $block ) {
		if ( file_exists( get_stylesheet_directory() . '/blocks/' . $block . '/block.json' ) ) {
			register_block_type( get_stylesheet_directory() . '/blocks/' . $block . '/block.json' );
		}
	}
}
add_action( 'init', __NAMESPACE__ . '\\load_blocks', 5 );

/**
 * Load ACF field groups for blocks.
 *
 * @param [type] $paths
 *
 * @return void
 * @author Rob Migchels <rob@migchels.me>
 */
function load_acf_field_group( $paths ) {
	$blocks = get_blocks();
	foreach ( $blocks as $block ) {
		$paths[] = get_stylesheet_directory() . '/blocks/' . $block;
	}
	return $paths;
}
add_filter( 'acf/settings/load_json', __NAMESPACE__ . '\\load_acf_field_group' );

/**
 * Get Blocks.
 *
 * @return void
 * @author Rob Migchels <rob@migchels.me>
 */
function get_blocks() {
	$blocks = scandir( get_stylesheet_directory() . '/blocks/' );
	$blocks = array_values( array_diff( $blocks, array( '..', '.', '.DS_Store', '_base-block' ) ) );
	return $blocks;
}

/**
 * Prevent the help text output by ACF which tells the user to add ACF fields to blocks without ACF fields.
 * This is disabled, because not all blocks require ACF fields. Sometimes, we just want to display something
 * that was generated by PHP or is not dynamic at all.
 *
 * @see https://www.advancedcustomfields.com/resources/whats-new-with-acf-blocks-in-acf-6/#blocks-without-fields
 */
add_filter( 'acf/blocks/no_fields_assigned_message', '__return_empty_string' );
